"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { authButtonClass, authInputClass } from "@/components/auth/AuthShell";
export default function ResetPasswordForm() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function sendCode() { setError(""); const response = await fetch("/api/auth/send-code", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, purpose: "reset" }) }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "发送失败"); else setMessage("如账号存在，验证码已发送至企业邮箱"); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/auth/reset-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error || "重置失败"); setLoading(false); return; } router.replace("/login"); }
  return <form onSubmit={submit} className="space-y-4"><div><label className="mb-1.5 block text-sm font-bold text-[#344054]">企业邮箱</label><input className={authInputClass} name="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div className="grid grid-cols-[1fr_auto] gap-2"><input className={authInputClass} name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="6位验证码" required /><button type="button" onClick={sendCode} className="border border-[#4870ff] px-3 text-sm font-bold text-[#032a72]">发送验证码</button></div><input className={authInputClass} name="password" type="password" minLength={8} maxLength={128} placeholder="新密码（至少8位）" required /><input className={authInputClass} name="confirmPassword" type="password" minLength={8} maxLength={128} placeholder="确认新密码" required />{message && <p className="bg-blue-50 px-3 py-2 text-sm text-[#032a72]">{message}</p>}{error && <p className="border-l-4 border-red-500 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button className={authButtonClass} disabled={loading}>{loading ? "处理中…" : "重置密码"}</button></form>;
}
